import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const sourceRoot = `${root}src/ui/tokens/source`;
const outputPath = `${root}src/ui/tokens/tokens.css`;
const componentsPath = `${root}src/ui/tokens/components.css`;
const contractPath = `${root}src/ui/tokens/contract.generated.ts`;

const readJson = async (name) => JSON.parse(await readFile(`${sourceRoot}/${name}`, "utf8"));
const [foundations, primitives, light, dark, components] = await Promise.all([
  readJson("foundations.tokens.json"),
  readJson("primitives.tokens.json"),
  readJson("semantic-light.tokens.json"),
  readJson("semantic-dark.tokens.json"),
  readJson("components.tokens.json"),
]);

const value = (token) => token.$value;
const color = (token) => value(token).hex.toLowerCase();
const px = (token) => `${value(token)}px`;
const semantic = (source) => ({
  "background-page": color(source.Background.Page),
  "background-subtle": color(source.Background.Subtle),
  "background-raised": color(source.Background.Raised),
  "text-primary": color(source.Text.Primary),
  "text-secondary": color(source.Text.Secondary),
  "text-disabled": color(source.Text.Disabled),
  "border-subtle": color(source.Border.Subtle),
  "border-default": color(source.Border.Default),
  "border-strong": color(source.Border.Strong),
  "state-selected": color(source.State.Selected.Container),
  "state-disabled": color(source.State.Disabled.Container),
  "error-container": color(source.State.Error.Container),
  "error-border": color(source.State.Error.Border),
  "error-text": color(source.State.Error.Text),
  "action-primary-subtle": color(source.Action.Primary.Subtle),
  "action-primary-subtle-hover": color(source.Action.Primary.SubtleHover),
  "action-primary-border": color(source.Action.Primary.Border),
  "action-primary-default": color(source.Action.Primary.Default),
  "action-primary-hover": color(source.Action.Primary.Hover),
  "action-primary-pressed": color(source.Action.Primary.Pressed),
  "action-primary-text": color(source.Action.Primary.Text),
  "action-secondary-subtle": color(source.Action.Secondary.Subtle),
  "action-secondary-subtle-hover": color(source.Action.Secondary.SubtleHover),
  "action-secondary-border": color(source.Action.Secondary.Border),
  "action-secondary-default": color(source.Action.Secondary.Default),
  "action-secondary-hover": color(source.Action.Secondary.Hover),
  "action-secondary-pressed": color(source.Action.Secondary.Pressed),
  "action-secondary-text": color(source.Action.Secondary.Text),
});

const declarations = (tokens, prefix = "--uf-color-") =>
  Object.entries(tokens).map(([name, token]) => `  ${prefix}${name}: ${token};`).join("\n");

const spacing = Object.fromEntries(Object.entries(foundations.Spacing).map(([name, token]) => [name, px(token)]));
const radius = Object.fromEntries(Object.entries(foundations.Radius).filter(([, token]) => token.$value !== undefined).map(([name, token]) => [name, px(token)]));
const control = Object.fromEntries(Object.entries(foundations.Size.Control).map(([name, token]) => [name, px(token)]));
const icon = Object.fromEntries(Object.entries(foundations.Size.Icon).map(([name, token]) => [name, px(token)]));
const border = Object.fromEntries(Object.entries(foundations.BorderWidth).map(([name, token]) => [name, px(token)]));
const primitiveColors = Object.fromEntries(
  Object.entries(primitives)
    .filter(([family]) => family !== "$extensions")
    .flatMap(([family, steps]) =>
      Object.entries(steps).map(([step, token]) => [`${family.toLowerCase()}-${step}`, color(token)]),
    ),
);

const fonts = {
  heading: `${JSON.stringify(value(foundations.FontFamily.Heading))}, sans-serif`,
  body: `${JSON.stringify(value(foundations.FontFamily.Body))}, sans-serif`,
  mono: `${JSON.stringify(value(foundations.FontFamily.Mono))}, monospace`,
};
const motion = { fast: "100ms", normal: "180ms", slow: "320ms" };

const css = `/* Generated by npm run tokens:build. Edit the JSON sources, not this file. */
:root,
[data-uiforma-theme="light"] {
${declarations(semantic(light))}
}

[data-uiforma-theme="dark"] {
${declarations(semantic(dark))}
}

:root {
${declarations(primitiveColors, "--uf-color-")}
${declarations(spacing, "--uf-space-")}
${declarations(radius, "--uf-radius-")}
${declarations(control, "--uf-control-")}
${declarations(icon, "--uf-icon-")}
${declarations(border, "--uf-border-")}
${declarations(fonts, "--uf-font-")}
${declarations(motion, "--uf-motion-")}
}
`;

const componentGroups = Object.entries(components).filter(([group]) => !group.startsWith("$"));
const componentTokens = componentGroups.flatMap(([group, tokens]) =>
  Object.entries(tokens).map(([name, tokenValue]) => ({ group, name: `--uf-${group}-${name}`, value: tokenValue })),
);

// :where() keeps defaults at zero specificity so any theme file wins, and re-declaring them on
// [data-uiforma-theme] lets colour references follow light/dark scopes instead of inheriting
// values already resolved at the root.
const componentsCss = `/* Generated by npm run tokens:build. Edit source/components.tokens.json, not this file. */
:where(:root, [data-uiforma-theme]) {
${componentTokens.map(({ name, value: tokenValue }) => `  ${name}: ${tokenValue};`).join("\n")}
}
`;

const entry = (layer, group, name, lightValue, darkValue) =>
  `  { name: ${JSON.stringify(name)}, layer: ${JSON.stringify(layer)}, group: ${JSON.stringify(group)}, value: ${JSON.stringify(lightValue)}${darkValue === undefined || darkValue === lightValue ? "" : `, dark: ${JSON.stringify(darkValue)}`} },`;
const scale = (group, prefix, tokens) =>
  Object.entries(tokens).map(([name, tokenValue]) => entry("primitive", group, `${prefix}${name}`, tokenValue));
const lightSemantic = semantic(light);
const darkSemantic = semantic(dark);
const contractEntries = [
  ...Object.entries(lightSemantic).map(([name, tokenValue]) =>
    entry("semantic", "color", `--uf-color-${name}`, tokenValue, darkSemantic[name]),
  ),
  ...scale("color", "--uf-color-", primitiveColors),
  ...scale("space", "--uf-space-", spacing),
  ...scale("radius", "--uf-radius-", radius),
  ...scale("control", "--uf-control-", control),
  ...scale("icon", "--uf-icon-", icon),
  ...scale("border", "--uf-border-", border),
  ...scale("font", "--uf-font-", fonts),
  ...scale("motion", "--uf-motion-", motion),
  ...componentTokens.map(({ group, name, value: tokenValue }) => entry("component", group, name, tokenValue)),
];

const contract = `/* Generated by npm run tokens:build. Edit the JSON sources, not this file. */
import type { UIFormaThemeToken } from "./contract";

export const UI_FORMA_THEME_TOKENS: readonly UIFormaThemeToken[] = [
${contractEntries.join("\n")}
];
`;

const outputs = [
  [outputPath, css],
  [componentsPath, componentsCss],
  [contractPath, contract],
];

if (process.argv.includes("--check")) {
  for (const [path, expected] of outputs) {
    const current = await readFile(path, "utf8").catch(() => "");
    if (current !== expected) {
      console.error(`${path.replace(root, "")} is stale. Run npm run tokens:build.`);
      process.exitCode = 1;
    }
  }
} else {
  for (const [path, contents] of outputs) {
    await writeFile(path, contents);
    console.log(`Generated ${path.replace(root, "")}`);
  }
}
