import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const sourceRoot = `${root}src/ui/tokens/source`;
const outputPath = `${root}src/ui/tokens/tokens.css`;

const readJson = async (name) => JSON.parse(await readFile(`${sourceRoot}/${name}`, "utf8"));
const [foundations, primitives, light, dark] = await Promise.all([
  readJson("foundations.tokens.json"),
  readJson("primitives.tokens.json"),
  readJson("semantic-light.tokens.json"),
  readJson("semantic-dark.tokens.json"),
]);

const value = (token) => token.$value;
const color = (token) => value(token).hex.toLowerCase();
const px = (token) => `${value(token)}px`;
const semantic = (source) => ({
  "background-page": color(source.Background.Page),
  "background-subtle": color(source.Background.Subtle),
  "background-raised": color(source.Background.Raised),
  "text-primary": color(source.Text.Primary),
  "text-secondary": color(source.Text.Secondary),
  "text-disabled": color(source.Text.Disabled),
  "border-subtle": color(source.Border.Subtle),
  "border-default": color(source.Border.Default),
  "border-strong": color(source.Border.Strong),
  "state-selected": color(source.State.Selected.Container),
  "state-disabled": color(source.State.Disabled.Container),
  "error-container": color(source.State.Error.Container),
  "error-border": color(source.State.Error.Border),
  "error-text": color(source.State.Error.Text),
  "action-primary-subtle": color(source.Action.Primary.Subtle),
  "action-primary-subtle-hover": color(source.Action.Primary.SubtleHover),
  "action-primary-border": color(source.Action.Primary.Border),
  "action-primary-default": color(source.Action.Primary.Default),
  "action-primary-hover": color(source.Action.Primary.Hover),
  "action-primary-pressed": color(source.Action.Primary.Pressed),
  "action-primary-text": color(source.Action.Primary.Text),
  "action-secondary-subtle": color(source.Action.Secondary.Subtle),
  "action-secondary-subtle-hover": color(source.Action.Secondary.SubtleHover),
  "action-secondary-border": color(source.Action.Secondary.Border),
  "action-secondary-default": color(source.Action.Secondary.Default),
  "action-secondary-hover": color(source.Action.Secondary.Hover),
  "action-secondary-pressed": color(source.Action.Secondary.Pressed),
  "action-secondary-text": color(source.Action.Secondary.Text),
});

const declarations = (tokens, prefix = "--uf-color-") =>
  Object.entries(tokens).map(([name, token]) => `  ${prefix}${name}: ${token};`).join("\n");

const spacing = Object.fromEntries(Object.entries(foundations.Spacing).map(([name, token]) => [name, px(token)]));
const radius = Object.fromEntries(Object.entries(foundations.Radius).filter(([, token]) => token.$value !== undefined).map(([name, token]) => [name, px(token)]));
const control = Object.fromEntries(Object.entries(foundations.Size.Control).map(([name, token]) => [name, px(token)]));
const icon = Object.fromEntries(Object.entries(foundations.Size.Icon).map(([name, token]) => [name, px(token)]));
const border = Object.fromEntries(Object.entries(foundations.BorderWidth).map(([name, token]) => [name, px(token)]));
const primitiveColors = Object.fromEntries(
  Object.entries(primitives)
    .filter(([family]) => family !== "$extensions")
    .flatMap(([family, steps]) =>
      Object.entries(steps).map(([step, token]) => [`${family.toLowerCase()}-${step}`, color(token)]),
    ),
);

const css = `/* Generated by npm run tokens:build. Edit the JSON sources, not this file. */
:root,
[data-uiforma-theme="light"] {
${declarations(semantic(light))}
}

[data-uiforma-theme="dark"] {
${declarations(semantic(dark))}
}

:root {
${declarations(primitiveColors, "--uf-color-")}
${declarations(spacing, "--uf-space-")}
${declarations(radius, "--uf-radius-")}
${declarations(control, "--uf-control-")}
${declarations(icon, "--uf-icon-")}
${declarations(border, "--uf-border-")}
  --uf-font-heading: ${JSON.stringify(value(foundations.FontFamily.Heading))}, sans-serif;
  --uf-font-body: ${JSON.stringify(value(foundations.FontFamily.Body))}, sans-serif;
  --uf-font-mono: ${JSON.stringify(value(foundations.FontFamily.Mono))}, monospace;
  --uf-motion-fast: 100ms;
  --uf-motion-normal: 180ms;
  --uf-motion-slow: 320ms;
}
`;

if (process.argv.includes("--check")) {
  const current = await readFile(outputPath, "utf8").catch(() => "");
  if (current !== css) {
    console.error("tokens.css is stale. Run npm run tokens:build.");
    process.exitCode = 1;
  }
} else {
  await writeFile(outputPath, css);
  console.log("Generated src/ui/tokens/tokens.css");
}
